spring:
  datasource:
    url: jdbc:mysql://mysql:3306/micro_db?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
    show-sql: true

server:
  error:
    include-binding-errors: always
    include-message: always
  port: 8081
